### ISSUE TITLE
'Copy Link` doesn't source any version for the hyperlink

### ISSUE THREAD

**Issue by aeu485** [dfreiberger/tc-preview-extension#18]
![image](https://github.com/dfreiberger/tc-preview-extension/assets/100540732/6133ba81-813b-4b71-b161-78d45b272f22)
The `copy link` button doesn't source any path via which the code should be viewed. Use of the hyperlink will default to the last branch selected while viewing the repository. Path should be sourced in two different ways:
* When viewed from the file explorer (`version=GB<!BRANCH_NAME>`)
* When viewed from a pull request (`_git/<!REPO_NAME>/pullrequest/<!PR_#>`)

**Comment by dfreiberger** [comment]
@aeu485 this should be fixed in the latest version. Thank you for reporting!
